// =============================================================================
// Python → TS conformance — reverse-direction cross-language verification.
//
// Loads fixtures generated by `python/scripts/generate_python_fixtures.py`
// (committed at python/tests/fixtures/python-generated/) and verifies them
// under the TS implementation. Together with conformance.test.ts (which goes
// TS → Python), this closes the cross-language loop both ways.
//
// If you regenerate the Python fixtures, expect this test file to keep
// passing. If it doesn't, the two implementations have diverged on the spec.
// =============================================================================

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { verifyChain, computeEntryHash, sha256, serializeState } from "../snapshot.js";
import type { LedgerEntry } from "../protocol.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PY_FIXTURES = join(
  __dirname,
  "..",
  "..",
  "python",
  "tests",
  "fixtures",
  "python-generated"
);

interface Fixture {
  protocol: string;
  version: string;
  entries: LedgerEntry[];
}

function loadFixture(name: string): Fixture {
  return JSON.parse(readFileSync(join(PY_FIXTURES, name), "utf8"));
}

const fixtures = existsSync(PY_FIXTURES)
  ? readdirSync(PY_FIXTURES).filter((f) => f.endsWith(".json")).sort()
  : [];

describe("python-generated fixtures present", () => {
  it("at least one Python-generated fixture is committed", () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });
});

describe.each(fixtures)("python-generated fixture %s", (name) => {
  const fixture = loadFixture(name);

  it("declares MAP protocol and matching major.minor", () => {
    expect(fixture.protocol).toBe("map");
    expect(fixture.version).toBe("0.1.0");
  });

  it("verifies as a valid chain under the TS implementation", () => {
    expect(verifyChain(fixture.entries)).toEqual({ valid: true });
  });

  it("recomputes each entry's hash to the stored value", () => {
    for (const e of fixture.entries) {
      const expected = computeEntryHash(
        e.sequence,
        e.action,
        e.stateBefore,
        e.stateAfter,
        e.parentHash,
        e.critic
      );
      expect(e.hash).toBe(expected);
    }
  });

  it("recomputes each state hash from the embedded snapshot", () => {
    for (const e of fixture.entries) {
      expect(e.stateBefore).toBe(sha256(serializeState(e.snapshots.before)));
      expect(e.stateAfter).toBe(sha256(serializeState(e.snapshots.after)));
    }
  });
});

// ─── Negative tests on Python-generated ledgers ─────────────────────────────

describe("structural tampering of python-generated fixtures", () => {
  it.each(fixtures)("detects field tampering in %s", (name) => {
    const fx = loadFixture(name);
    if (fx.entries.length === 0) return;
    const target = 0;
    const mutated = fx.entries.map((e, i) =>
      i === target ? { ...e, action: { ...e.action, tool: "tampered" } } : e
    );
    const result = verifyChain(mutated);
    expect(result.valid).toBe(false);
    expect(result.corruptedAt).toBe(target);
  });

  it.each(fixtures.filter((n) => loadFixture(n).entries.length >= 2))(
    "detects entry swap in %s",
    (name) => {
      const fx = loadFixture(name);
      const swapped = [...fx.entries];
      [swapped[0], swapped[1]] = [swapped[1], swapped[0]];
      const result = verifyChain(swapped);
      expect(result.valid).toBe(false);
      expect(result.corruptedAt).toBe(0);
    }
  );

  it.each(fixtures.filter((n) => loadFixture(n).entries.length >= 2))(
    "detects entry deletion in %s",
    (name) => {
      const fx = loadFixture(name);
      const truncated = [fx.entries[0], ...fx.entries.slice(2)];
      const result = verifyChain(truncated);
      expect(result.valid).toBe(false);
      expect(result.corruptedAt).toBe(1);
    }
  );
});
